#!/usr/bin/python3
def raise_exception():
    me = "2" + 3
